services:
  geosatellite:
    build: ./GeoSatellite
    env_file:
      - ./GeoSatellite/.env
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  geotiles:
    build: ./GeoTiles
    env_file:
      - ./GeoTiles/.env
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  bts-downloader:
    build: ./GeoLayersBTS
    env_file:
      - ./GeoLayersBTS/.env
    volumes:
      - ./data:/app/KMZ
    restart: unless-stopped

  osm-downloader:
    platform: linux/amd64
    build: ./GeoKMZ
    volumes:
      - ./KMZ:/app/KMZ
      - ./OSM_Data:/app/OSM_Data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped